import { Project, Microservice, DiagramNode, DiagramConnection } from './store'

export const demoDiagramNodes: DiagramNode[] = [
  {
    id: 'node-client',
    type: 'client',
    label: 'Web & Mobile Client',
    x: 50,
    y: 50,
  },
  {
    id: 'node-gateway',
    type: 'gateway',
    label: 'API Gateway',
    x: 50,
    y: 150,
  },
  {
    id: 'node-auth',
    type: 'service',
    label: 'Auth Service',
    x: 10,
    y: 250,
  },
  {
    id: 'node-product',
    type: 'service',
    label: 'Product Service',
    x: 50,
    y: 250,
  },
  {
    id: 'node-order',
    type: 'service',
    label: 'Order Service',
    x: 90,
    y: 250,
  },
  {
    id: 'node-payment',
    type: 'service',
    label: 'Payment Service',
    x: 130,
    y: 250,
  },
  {
    id: 'node-db-auth',
    type: 'database',
    label: 'Auth DB (PostgreSQL)',
    x: 10,
    y: 380,
  },
  {
    id: 'node-db-product',
    type: 'database',
    label: 'Product DB (PostgreSQL)',
    x: 50,
    y: 380,
  },
  {
    id: 'node-db-order',
    type: 'database',
    label: 'Order DB (PostgreSQL)',
    x: 90,
    y: 380,
  },
  {
    id: 'node-payment-gateway',
    type: 'external',
    label: 'Payment Gateway (MTN/Vodafone)',
    x: 130,
    y: 380,
  },
  {
    id: 'node-cache',
    type: 'cache',
    label: 'Redis Cache',
    x: 170,
    y: 150,
  },
]

export const demoDiagramConnections: DiagramConnection[] = [
  {
    id: 'conn-1',
    from: 'node-client',
    to: 'node-gateway',
    protocol: 'HTTP/REST',
    label: 'API Requests',
  },
  {
    id: 'conn-2',
    from: 'node-gateway',
    to: 'node-auth',
    protocol: 'HTTP/REST',
    label: 'Authentication',
  },
  {
    id: 'conn-3',
    from: 'node-gateway',
    to: 'node-product',
    protocol: 'HTTP/REST',
    label: 'Product queries',
  },
  {
    id: 'conn-4',
    from: 'node-gateway',
    to: 'node-order',
    protocol: 'HTTP/REST',
    label: 'Order operations',
  },
  {
    id: 'conn-5',
    from: 'node-order',
    to: 'node-payment',
    protocol: 'HTTP/REST',
    label: 'Payment requests',
  },
  {
    id: 'conn-6',
    from: 'node-auth',
    to: 'node-db-auth',
    protocol: 'Database Connection',
    label: 'User data',
  },
  {
    id: 'conn-7',
    from: 'node-product',
    to: 'node-db-product',
    protocol: 'Database Connection',
    label: 'Product data',
  },
  {
    id: 'conn-8',
    from: 'node-order',
    to: 'node-db-order',
    protocol: 'Database Connection',
    label: 'Order data',
  },
  {
    id: 'conn-9',
    from: 'node-payment',
    to: 'node-payment-gateway',
    protocol: 'HTTP/REST',
    label: 'MTN/Vodafone',
  },
  {
    id: 'conn-10',
    from: 'node-product',
    to: 'node-cache',
    protocol: 'Cache Query',
    label: 'Caching',
  },
]

export const demoMicroservices: Microservice[] = [
  {
    id: 'auth-service',
    name: 'Authentication Service',
    responsibilities: 'User registration, login, JWT token generation, session management, role-based access control (RBAC)',
    entities: 'User, Session, Permission, Role, Token',
    endpoints: 'POST /auth/register, POST /auth/login, POST /auth/logout, GET /auth/verify, POST /auth/refresh',
    dependencies: 'None',
    databaseType: 'PostgreSQL',
  },
  {
    id: 'product-service',
    name: 'Product Service',
    responsibilities: 'Product catalog management, inventory tracking, search and filtering, category management, product recommendations',
    entities: 'Product, Category, Inventory, Review, Rating',
    endpoints: 'GET /products, GET /products/:id, POST /products (admin), PUT /products/:id (admin), DELETE /products/:id (admin), GET /products/search',
    dependencies: 'None',
    databaseType: 'PostgreSQL',
  },
  {
    id: 'order-service',
    name: 'Order Service',
    responsibilities: 'Order creation and management, order status tracking, order history, order validation, order cancellation',
    entities: 'Order, OrderItem, OrderStatus, ShippingAddress, Tracking',
    endpoints: 'POST /orders, GET /orders/:id, GET /orders/user/:userId, PUT /orders/:id/status, DELETE /orders/:id, GET /orders/:id/tracking',
    dependencies: 'Product Service, Payment Service, Notification Service',
    databaseType: 'PostgreSQL',
  },
  {
    id: 'payment-service',
    name: 'Payment Service',
    responsibilities: 'Payment processing, transaction management, payment validation, refund handling, integration with mobile money providers (MTN, Vodafone, AirtelTigo)',
    entities: 'Payment, Transaction, PaymentMethod, Refund, PaymentStatus',
    endpoints: 'POST /payments/process, GET /payments/:id, POST /payments/:id/refund, GET /payments/status/:reference, POST /payments/verify',
    dependencies: 'MTN Mobile Money API, Vodafone Cash API, External Payment Gateway',
    databaseType: 'PostgreSQL',
  },
  {
    id: 'notification-service',
    name: 'Notification Service',
    responsibilities: 'Email notifications, SMS alerts, push notifications, notification templates, notification history, user preferences',
    entities: 'Notification, NotificationTemplate, UserPreference, EmailLog, SMSLog',
    endpoints: 'POST /notifications/email, POST /notifications/sms, POST /notifications/push, GET /notifications/history/:userId, PUT /notifications/preferences/:userId',
    dependencies: 'Order Service, Payment Service, Email Provider, SMS Provider',
    databaseType: 'PostgreSQL',
  },
]

export const demoProject: Partial<Project> = {
  title: 'Scalable E-Commerce System Architecture',
  description: 'Architectural Design of a Scalable Web Services Platform for a Nationwide E-Commerce System',
  completedSections: ['A', 'B'],
  microservices: demoMicroservices,
  diagramNodes: demoDiagramNodes,
  diagramConnections: demoDiagramConnections,
  dataArchitectureNotes: 'Database Per Service pattern chosen for microservices scalability. Each service owns its data with eventual consistency through event-driven architecture.',
  sequenceFlowSteps: [
    'Customer places order through web/mobile app',
    'Order Service receives order and validates items with Product Service',
    'Order Service creates payment request to Payment Service',
    'Payment Service processes payment via MTN Mobile Money or Vodafone Cash',
    'Payment confirmed, Order Service updates order status',
    'Notification Service sends order confirmation to customer via email/SMS',
    'Order enters fulfillment queue for warehouse processing',
    'Delivery Service updates shipping information',
    'Final notification sent with tracking number',
  ],
  securityMeasures: {
    jwt: true,
    oauth2: false,
    encryption: true,
    rateLimiting: true,
    paymentSecurity: true,
    ddosProtection: false,
  },
  cloudComponents: [
    'AWS ELB (Load Balancer)',
    'AWS API Gateway',
    'EC2 Instances (App Servers)',
    'RDS PostgreSQL (Databases)',
    'ElastiCache Redis (Caching)',
    'S3 (Object Storage)',
    'CloudFront CDN',
    'AWS WAF (DDoS Protection)',
  ],
  costAnalysis: 'Estimated monthly cost: $1,500-$3,000 depending on traffic volume. Includes EC2, RDS, CDN, and support services. Can scale horizontally with load.',
}
